/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Materia;
import entidades.Alumno;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Damian
 */
public class Menu extends javax.swing.JFrame {
private HashSet<Alumno> listaAlumnos= new HashSet<>();
private HashSet<Materia> listaMaterias= new HashSet<>();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmFAlumnos = new javax.swing.JMenuItem();
        jmFMaterias = new javax.swing.JMenuItem();
        jmFInscripcion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmAcerca = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Operaciones");

        jmFAlumnos.setText("Formulario Alumnos");
        jmFAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jmFAlumnos);

        jmFMaterias.setText("Formulario Materias");
        jmFMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFMateriasActionPerformed(evt);
            }
        });
        jMenu1.add(jmFMaterias);

        jmFInscripcion.setText("Formulario de Inscripción");
        jmFInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFInscripcionActionPerformed(evt);
            }
        });
        jMenu1.add(jmFInscripcion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jmAcerca.setText("Acerca de...");
        jmAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAcercaActionPerformed(evt);
            }
        });
        jMenu2.add(jmAcerca);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jmSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFInscripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioInscripcion fI = new FormularioInscripcion(listaMaterias,listaAlumnos);
        fI.setVisible(true);
        escritorio.add(fI);
        escritorio.moveToFront(fI);
    }//GEN-LAST:event_jmFInscripcionActionPerformed

    private void jmFAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumnos fA = new FormularioAlumnos(listaAlumnos);
        fA.setVisible(true);
        escritorio.add(fA);
        escritorio.moveToFront(fA);
    }//GEN-LAST:event_jmFAlumnosActionPerformed

    private void jmFMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMaterias fM = new FormularioMaterias(listaMaterias);
        fM.setVisible(true);
        escritorio.add(fM);
        escritorio.moveToFront(fM);
    }//GEN-LAST:event_jmFMateriasActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Dario Damian CERATTO - Comisión 2");
    }//GEN-LAST:event_jmAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmAcerca;
    private javax.swing.JMenuItem jmFAlumnos;
    private javax.swing.JMenuItem jmFInscripcion;
    private javax.swing.JMenuItem jmFMaterias;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
